export const SCHEME_IDS = [
  "xiaohe",
  "apple-default",
  "sogou",
  "pinyin-jiajia",
  "microsoft",
  "common",
] as const;

export type SchemeId = (typeof SCHEME_IDS)[number];

export type ZeroInitialMode = "o-prefix" | "vowel-prefix" | "xiaohe-style";

export interface SchemeDefinition {
  id: SchemeId;
  title: string;
  shortTitle: string;
  initials: Readonly<Record<string, string>>;
  finals: Readonly<Record<string, string>>;
  zeroInitialMode: ZeroInitialMode;
}

const regularInitials = Object.fromEntries(
  ["b", "p", "m", "f", "d", "t", "n", "l", "g", "k", "h", "j", "q", "x", "r", "z", "c", "s", "y", "w"].map(
    (initial) => [initial, initial],
  ),
);

function initials(zh: string, ch: string, sh: string): Readonly<Record<string, string>> {
  return {
    ...regularInitials,
    zh,
    ch,
    sh,
  };
}

export const SCHEMES: Readonly<Record<SchemeId, SchemeDefinition>> = {
  "apple-default": {
    id: "apple-default",
    title: "Apple 默认",
    shortTitle: "默认",
    initials: initials("a", "e", "v"),
    zeroInitialMode: "o-prefix",
    finals: {
      a: "a",
      ai: "l",
      an: "j",
      ang: "h",
      ao: "k",
      e: "e",
      ei: "q",
      en: "f",
      eng: "g",
      er: "r",
      i: "i",
      ia: "d",
      ian: "w",
      iang: "t",
      iao: "z",
      ie: "x",
      in: "c",
      ing: "y",
      iong: "s",
      iu: "r",
      o: "o",
      ong: "s",
      ou: "b",
      u: "u",
      ua: "d",
      uai: "c",
      uan: "p",
      ue: "m",
      ui: "m",
      un: "n",
      uo: "o",
      uang: "t",
      ü: "v",
      üe: "v",
    },
  },
  sogou: {
    id: "sogou",
    title: "搜狗双拼",
    shortTitle: "搜狗",
    initials: initials("v", "i", "u"),
    zeroInitialMode: "o-prefix",
    finals: {
      a: "a",
      ai: "l",
      an: "j",
      ang: "h",
      ao: "k",
      e: "e",
      ei: "z",
      en: "f",
      eng: "g",
      er: "r",
      i: "i",
      ia: "w",
      ian: "m",
      iang: "d",
      iao: "c",
      ie: "x",
      in: "n",
      ing: ";",
      iong: "s",
      iu: "q",
      o: "o",
      ong: "s",
      ou: "b",
      u: "u",
      ua: "w",
      uai: "y",
      uan: "r",
      ue: "t",
      ui: "v",
      un: "p",
      uo: "o",
      uang: "d",
      ü: "y",
      üe: "t",
    },
  },
  "pinyin-jiajia": {
    id: "pinyin-jiajia",
    title: "拼音加加",
    shortTitle: "加加",
    initials: initials("v", "u", "i"),
    zeroInitialMode: "vowel-prefix",
    finals: {
      a: "a",
      ai: "s",
      an: "f",
      ang: "g",
      ao: "d",
      e: "e",
      ei: "w",
      en: "r",
      eng: "t",
      er: "q",
      i: "i",
      ia: "b",
      ian: "j",
      iang: "h",
      iao: "k",
      ie: "m",
      in: "l",
      ing: "q",
      iong: "y",
      iu: "n",
      o: "o",
      ong: "y",
      ou: "p",
      u: "u",
      ua: "b",
      uai: "x",
      uan: "c",
      ue: "x",
      ui: "v",
      un: "z",
      uo: "o",
      uang: "h",
      ü: "v",
      üe: "x",
    },
  },
  microsoft: {
    id: "microsoft",
    title: "微软双拼",
    shortTitle: "微软",
    initials: initials("v", "i", "u"),
    zeroInitialMode: "o-prefix",
    finals: {
      a: "a",
      ai: "l",
      an: "j",
      ang: "h",
      ao: "k",
      e: "e",
      ei: "z",
      en: "f",
      eng: "g",
      er: "r",
      i: "i",
      ia: "w",
      ian: "m",
      iang: "d",
      iao: "c",
      ie: "x",
      in: "n",
      ing: ";",
      iong: "s",
      iu: "q",
      o: "o",
      ong: "s",
      ou: "b",
      u: "u",
      ua: "w",
      uai: "y",
      uan: "r",
      ue: "t",
      ui: "v",
      un: "p",
      uo: "o",
      uang: "d",
      ü: "v",
      üe: "t",
    },
  },
  xiaohe: {
    id: "xiaohe",
    title: "小鹤双拼",
    shortTitle: "小鹤",
    initials: initials("v", "i", "u"),
    zeroInitialMode: "xiaohe-style",
    finals: {
      a: "a",
      ai: "d",
      an: "j",
      ang: "h",
      ao: "c",
      e: "e",
      ei: "w",
      en: "f",
      eng: "g",
      i: "i",
      ia: "x",
      ian: "m",
      iang: "l",
      iao: "n",
      ie: "p",
      in: "b",
      ing: "k",
      iong: "s",
      iu: "q",
      o: "o",
      ong: "s",
      ou: "z",
      u: "u",
      ua: "x",
      uai: "k",
      uan: "r",
      ue: "t",
      ui: "v",
      un: "y",
      uo: "o",
      uang: "l",
      ü: "v",
      üe: "t",
    },
  },
  common: {
    id: "common",
    title: "常用双拼",
    shortTitle: "常用",
    initials: initials("v", "i", "u"),
    zeroInitialMode: "xiaohe-style",
    finals: {
      a: "a",
      ai: "l",
      an: "j",
      ang: "h",
      ao: "k",
      e: "e",
      ei: "z",
      en: "f",
      eng: "g",
      i: "i",
      ia: "w",
      ian: "m",
      iang: "d",
      iao: "c",
      ie: "x",
      in: "n",
      ing: "y",
      iong: "s",
      iu: "q",
      o: "o",
      ong: "s",
      ou: "b",
      u: "u",
      ua: "w",
      uai: "y",
      uan: "r",
      ue: "t",
      ui: "v",
      un: "p",
      uo: "o",
      uang: "d",
      ü: "v",
      üe: "t",
    },
  },
};

export function isSchemeId(value: string): value is SchemeId {
  return (SCHEME_IDS as readonly string[]).includes(value);
}
